# Generated by Django 4.1.13 on 2026-04-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=255, verbose_name='nom de la société')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, verbose_name='SIRET')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('email_principal', models.EmailField(max_length=254, verbose_name='email principal')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone')),
                ('type_client', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CLIENT', 'Client')], default='PROSPECT', max_length=20, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telephone_direct', models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone direct')),
                ('poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='poste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm_core.client')),
            ],
        ),
    ]
