# Generated by Django 4.1.13 on 2026-04-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="titre de l'affaire")),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant estimé')),
                ('statut', models.CharField(choices=[('PROSPECT', 'Prospect'), ('QUALIFICATION', 'Qualification'), ('PROPOSITION', 'Proposition'), ('NEGOCIATION', 'Négociation'), ('GAGNE', 'Gagné'), ('PERDU', 'Perdu')], default='PROSPECT', max_length=20)),
                ('priorite', models.CharField(choices=[('LOW', 'Basse'), ('NORMAL', 'Normale'), ('HIGH', 'Haute')], default='NORMAL', max_length=10)),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="date d'échéance")),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm_core.client')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-updated_at'],
            },
        ),
    ]
