# Generated by Django 5.2.13 on 2026-04-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_client_owner'),
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users', to='crm_core.client'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Manager'), ('SALES', 'Commercial'), ('FINANCE', 'Finance'), ('SUPPORT', 'Support'), ('CLIENT', 'Client')], default='SALES', max_length=20),
        ),
    ]
